### ISSUE TITLE
Symfony 4 integration

### ISSUE THREAD

**Issue by vcalaelen** [biig-io/DomainComponent#11]
@Nek-  I can't seem to get it to work with Symfony 4.1. 
I've added the following `config/packages/biig_domain.yaml`:
```yaml
biig_domain:
    # It modifies the DoctrineBundle configuration to register a new
    # ClassMetadataInfo class so the instantiator now set the domain event
    # dispatcher to your models automatically
    override_doctrine_instantiator: true

    # By default it will override the doctrine instantiator only for
    # the "default" entity manager of your application. You can specify
    # many entity managers if you want.
    entity_managers: []

    # Post persist events are not activated by default, you need to enable the post persist listeners
    persist_listeners:
        # As doctrine supports many connections, you need to enable your connections one by one
        doctrine: ['default']
```
My Listener:
```php
<?php
namespace App\Application\EventListeners;

use Biig\Component\Domain\Event\DomainEvent;
use Biig\Component\Domain\Rule\PostPersistDomainRuleInterface;

class VerificationCreatedListener implements PostPersistDomainRuleInterface {

	/**
	 * Returns an array of event or a string it listen on.
	 *
	 * @return array|string
	 */
	public function after() {
		return 'vc.created';
	}

	/**
	 * @param DomainEvent $event
	 */
	public function execute( DomainEvent $event ) {
		var_dump( $event ); die;
	}
}
```

My Entity:
```php
<?php
namespace App\Application\Entity;

use App\Application\Entity\VerificationCode\MobileNumber;
use App\Application\Entity\VerificationCode\SecretCode;
use Biig\Component\Domain\Event\DomainEvent;
use Biig\Component\Domain\Model\DomainModel;

class VerificationCode extends DomainModel {
	/**
	 * @var int
	 */
	private $id;

	/**
	 * @var MobileNumber
	 */
	private $mobileNumber;

	/**
	 * @var SecretCode
	 */
	private $code;

	public function __construct( $id, MobileNumber $mobileNumber, SecretCode $code ) {
		$this->id = $id;
		$this->mobileNumber = $mobileNumber;
		$this->code = $code;

		$this->dispatch('vc.created', new DomainEvent($this));
	}

	public function id() {
		return $this->id;
	}

	public function mobileNumber(): MobileNumber {
		return $this->mobileNumber;
	}

	public function code(): SecretCode {
		return $this->code;
	}

	public function shouldSendNewCode(): bool {
		return !$this->code->isSent() || $this->code->isExpired();
	}
}
```

The `execute` method is never called. It seems the instantiator is not being set. Am I missing something in the configuration?
